- name: Install specified mergerfs version
  when: mergerfs_release_type | length > 0
  tags: mergerfs
  block:
    - name: Grab mergerfs release list from GitHub
      ansible.builtin.uri:
        url: https://api.github.com/repos/trapexit/mergerfs/releases/latest
        method: GET
      register: github_release
      delegate_to: localhost

    - name: Create query filter
      ansible.builtin.set_fact:
        query_filter: "assets[?ends_with(name,'{{ mergerfs_release_type }}')]"

    - name: Identify download URL from release list
      ansible.builtin.set_fact:
        file_name: "{{ release_latest.name }}"
        download_url: "{{ release_latest.browser_download_url }}"
      vars:
        release_latest: "{{ github_release.json | to_json | from_json | json_query(query_filter) | first }}"

    - name: Install package {{ file_name }}
      ansible.builtin.apt:
        deb: "{{ download_url }}"
